In [28]:
my_list = [1,2,0,0,4,0]
non_zero_indices = [i for i, val in enumerate(my_list) if val!=0] # With lists
my_array = np.array(my_list)
non_zero_indices_np = np.nonzero(my_array) # With arrays
print(non_zero_indices)
print(non_zero_indices_np)
print(my_array[non_zero_indices_np])

[0, 1, 4]
(array([0, 1, 4], dtype=int64),)
[1 2 4]


In [31]:
N = 10 # Array sizes
array = np.ones((N,N)) # Create array of ones
array[1:-1, 1:-1] = 0 # Empty the values not on border
print(array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [41]:
checkerboard = np.array([[1 if i%2==j%2 else 0 for i in range(8)] for j in range(8)])
print(checkerboard)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [42]:
Z = np.arange(11)
Z[3:8] *= -1
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [43]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.view('float32')
print(Z.dtype)

int32
float32


In [45]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(C)
print(D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]


In [46]:
tile = [[1,0],[0,1]]
checkerboard_from_tile = np.tile(tile, (4,4))
print(checkerboard_from_tile)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [49]:
Z = np.arange(11)
Z[3:8] *= -1 # Negating elements between 3rd and 8th indices
print(Z)

Z = np.arange(11)
Z[(Z >= 3) & (Z < 8)] *= -1 # Negating elements based on their values (between 3 and 8)
print(Z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


In [50]:
Z = np.random.random(10)
Z = np.sort(Z)
print(Z)

[0.13197721 0.17045175 0.17235228 0.31390614 0.32901831 0.38673589
 0.46281756 0.52504866 0.84990624 0.96989423]


In [51]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = (A==B).all()
print(equal)


False


In [52]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)
Z = Z.view('float32')
print(Z.dtype)

int32
float32


In [53]:
A = np.arange(9).reshape(3,3)
B = A + 1
C = np.dot(A,B)
D = np.diag(C)
print(C) # Show the matrix to check we are indeed getting the diagonal
print(D)

[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[ 18  66 132]
