In [7]:
p = [[1.0, 2.0, 10],
     [3.0, 4.0, 20],
     [5.0, 6.0, 30],
     [7.0, 8.0, 40]]
# Normalise each coordinate by dividing with its Z (3rd) element. For example, the first row becomes:
# `[1/10, 2/10, 10/10]`
# Hint: extract the last column into a variable z, and then change its dimensions so that p / z works.
import numpy as np
p = np.array(p)
p = p/p[:,-1][:, np.newaxis]
print(p)

[[0.1        0.2        1.        ]
 [0.15       0.2        1.        ]
 [0.16666667 0.2        1.        ]
 [0.175      0.2        1.        ]]


In [18]:
array = np.random.rand(3,3) # Create array
diagonal = array[range(3),range(3)] # access diagonal elements
print(array)
print(diagonal)

[[0.54261197 0.01648213 0.82807829]
 [0.46406435 0.98399719 0.82246122]
 [0.40655616 0.63793567 0.6814359 ]]
[0.54261197 0.98399719 0.6814359 ]


In [27]:
import numpy as np
array = np.random.rand(10,3)
j = []
for row in array:
    j.append(np.argmin(np.abs(row-0.75)))
print("Column indices: ", j)
print("Closest values: ", array[range(10),j])

Column indices:  [2, 0, 1, 1, 2, 0, 1, 1, 0, 0]
Closest values:  [0.57197039 0.86977013 0.50703856 0.60788132 0.93303445 0.14890818
 0.80635451 0.76882804 0.81424667 0.97199081]


In [2]:
import numpy as np
array = np.random.rand(10,3)
array[range(10), ]
np.argmin(np.abs(array-0.75))
# print("Column indices: ", j)
# print("Closest values: ", array[range(10),j])

5

In [5]:
import numpy as np
array = np.random.rand(10,3)

array([9, 5, 9], dtype=int64)

In [15]:
array = np.random.rand(10,3)
j = np.argmin(np.abs(array-0.75), axis=1)
closest_values = array[range(10), j]
print("Column indices: ", j)
print("Closest values: ", closest_values)

Column indices:  [1 2 2 2 1 1 0 0 1 2]
Closest values:  [0.44878575 0.7973273  0.68254201 0.38388891 0.70429783 0.71634223
 0.98655728 0.87407857 0.82124707 0.94627131]


In [16]:
print(array)

[[0.08336952 0.44878575 0.21810328]
 [0.81995102 0.8899318  0.7973273 ]
 [0.01694503 0.24999743 0.68254201]
 [0.28228752 0.09907938 0.38388891]
 [0.26428887 0.70429783 0.32091132]
 [0.59214984 0.71634223 0.52545236]
 [0.98655728 0.13297756 0.053452  ]
 [0.87407857 0.18553112 0.22308024]
 [0.86669762 0.82124707 0.27217017]
 [0.08864316 0.14209958 0.94627131]]


In [27]:
x = np.empty((10, 8, 6))

idx0 = np.zeros((3, 8)).astype(int)
idx1 = np.zeros((3, 1)).astype(int)
idx1_prime = np.zeros((3)).astype(int)
idx2 = np.zeros((1, 1)).astype(int)

In [34]:
# Predictions: x has shape 10 x 8 x 6
# x[idx0,:,:] should have shape (3 x 8) x (8 x 6), since we set the first entry of x to 3 x 8 values, and for each value we get a 8 x 6 matrix back
print("Check prediction (3 x 8 x 8 x 6): ", x[idx0,:,:].shape)
# x[idx0,idx1,:] should have shape Broadcast((3 x 8), (3 x 1)) x (6), since we set the first entry of x to 3 x 8 values, the second to 3 x 1 values simultaneously, and for each value we get an array of length (6) back. The broadcast results in Broadcast((3 x 8), (3 x 1)) = 3 x 8, so the final shape is 3 x 8 x 6.
print("Check prediction (3 x 8 x 6): ", x[idx0,idx1,:].shape)
# x[idx0,idx1,idx2] should have shape Broadcast((3 x 8), (3 x 1), (1 x 1)) x (), since we set the first entry of x to 3 x 8 values, the second to 3 x 1 values and the third to 1 x 1 simultaneously, and for each value we get a number back. The broadcast results in Broadcast((3 x 8), (3 x 1), (1 x 1)) = 3 x 8, so the final shape is 3 x 8.
print("Check prediction (3 x 8): ", x[idx0,idx1,idx2].shape)

Check prediction (3 x 8 x 8 x 6):  (3, 8, 8, 6)
Check prediction (3 x 8 x 6):  (3, 8, 6)
Check prediction (3 x 8):  (3, 8)
